# Generated by Django 5.1.4 on 2025-02-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reward',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
