# Generated by Django 5.1.4 on 2025-01-05 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='bodyText',
            new_name='body_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_name',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
