# Generated by Django 5.1.4 on 2025-02-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
