# Generated by Django 5.1.4 on 2025-02-03 04:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_longtitude_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_name',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
