# Generated by Django 5.1.4 on 2025-02-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_foundpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoundPost',
        ),
    ]
